FROM node
WORKDIR /app
COPY . .
RUN npm install
ENV REGISTRATION_SERVICE /.env?REGISTRATION_SERVICE
ENV BLOG_SERVICE /.env?BLOG_SERVICE
ENV MESSAGE_SERVICE /.env?MESSAGE_SERVICE
ENV MY_PORT /.env?MY_PORT
#RUN -p 5004:5004
CMD ["node", "index.js"]